name: Build Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-image: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Solution
      run: go build -o allopopot-interconnect-service
  
    - name: Build Container using Podman
      run: podman build -f=./Containerfile -t container-registry.allopopot.com/allopopot-interconnect-service

    - name: Push Container to Registry
      run: podman push container-registry.allopopot.com/allopopot-interconnect-service