name: Build Image and Push to Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu
    env:
      CONTAINER_REGISTRY_URL: ${{ secrets.CONTAINER_REGISTRY_URL }}
      SERVICE_NAME: allopopot-interconnect-service
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.24'          

      - name: Connect to Infrastructure (Tailscale)
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Build Application
        run: go build

      - name: Build Container using Podman
        run: podman build -f=./Containerfile --env=MONGODB_URI -t $CONTAINER_REGISTRY_URL/$SERVICE_NAME

      - name: Push Container to Registry
        run: podman push $CONTAINER_REGISTRY_URL/$SERVICE_NAME